# remote_theme: pages-themes/slate@v0.2.0
remote_theme: https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
- jekyll-remote-theme
title: Chris's homepage
description: Bookmark this to keep an eye on my project updates!
